### ISSUE TITLE
Extreme memory usage

### ISSUE THREAD

**Issue by oldenburg1990** [pauljeannot/SnapSliderFilters#1]
Hey man,

Great project, but there is one problem - when running in the emulator via xcode it has a memory use of around 89+ MB. When tested on a real iphone 6 this translates into lost connection crashes due to extreme memory usage. Hope you get a chance to look into this

// Jonas

**Comment by pauljeannot** [comment]
Hi, thank you for the report !

I saw that indeed, but if you run the app without the cable, nothing is happening - no warning. I'm going to look deeper into this issue this week, I will get back to you soon !

Paul

**Comment by alejandrorbradford** [comment]
Excellent repo! Is there any way you can get back the edited image with text and filter (just like the user sees it) back as UIimage?

**Comment by pauljeannot** [comment]
Hi guys,

@alejandrorbradford  : To get back the edited image, you can use the function written in SNUtils : 
`public static func screenShot(view: UIView) -> UIImage`

@oldenburg1990 : Sorry for the delay! I'm currently working on the issue, a fix will be available soon !

**Comment by pauljeannot** [comment]
@oldenburg1990 Here is my report : I didn't manage to reproduce that warning, and no memory warning is currently happening (iPhone 5/6, different cables and simulators). I think that strange behavior was due to the cable, because without it nothing was happening. 

I have also checked for memory leaks or extreme memory usage but nothing to report.

**Edit :** However, it might occurs if you try to compute a too big image : try to resize it before generating the filters. You can find an example of that in the example project when importing an image from the camera roll, or just follow this [link](http://stackoverflow.com/a/29138120/4001337) !

Paul
