### ISSUE TITLE
Using Custom Image From Camera

### ISSUE THREAD

**Issue by wdctaylor** [pauljeannot/SnapSliderFilters#2]
Hello, 

I am trying to use an image from a captured camera image. I have plugged it in succesfully. But one, the image does not scale properly, and secondly after a few swipes through the filters my application crashes... Any suggestions? 

Here is how I plugged in my image into the withImage Paramater:

self.data = SNFilter.generateFilters(SNFilter(frame: self.slider.frame, withImage: image, filters: SNFilter.filterNameList)

Other than that, running it with the default image you provided works like a charm..

Thanks!

**Comment by pauljeannot** [comment]
Hi @wdctaylor, sorry for the delay !

I faced that strange behavior about the scale issue, but without crash. Are you sure that the captured image is properly instanced ? Can you show the image within a UIImageView  ?

To deal with the scale issue, you can edit the way images are rendered to generate the filters. The following code can replace the 6th step in **SNFilter.swift** :

``` swift
func applyFilter(filterNamed name:String) -> SNFilter
```

``` swift
// 6 - convert filtered CGImage to UIImage
var filteredImage = UIImage(CGImage: outputCGImage, scale: 1.0, orientation: UIImageOrientation.Right)
if (isFrontCamera) {
   filteredImage = flipH(filteredImage)
}
```

``` swift
static func flipH(im:UIImage)->UIImage {
  var newOrient:UIImageOrientation
  switch im.imageOrientation {
        case .Up:
            newOrient = .UpMirrored
        case .UpMirrored:
            newOrient = .Up
        case .Down:
            newOrient = .DownMirrored
        case .DownMirrored:
            newOrient = .Down
        case .Left:
            newOrient = .RightMirrored
        case .LeftMirrored:
            newOrient = .Right
        case .Right:
            newOrient = .LeftMirrored
        case .RightMirrored:
            newOrient = .Left
  }
   return UIImage(CGImage: im.CGImage!, scale: im.scale, orientation: newOrient)
}
```

**Edit :** I faced the issue but I found the solution [there](http://stackoverflow.com/a/29138120/4001337). 

If you have still some troubles with it, you can also look at [this link](http://stackoverflow.com/a/31929631/4001337)

In addition, I think your app crashed because of a too big memory usage : captured images are much bigger than the default provided one ! Resizing the image before computing the filters did the trick for me!

Here is the final working code to setup your custom image : 

``` swift
let newImage = pickedImage.resizeWithWidth(SNUtils.screenSize.width) // method in the first link above
if let image = newImage {
      updatePicture(image)
}
```

I hope that will solve your problem !
Paul
