### ISSUE TITLE
Avoid resizing before adding the filters?

### ISSUE THREAD

**Issue by ghost** [pauljeannot/SnapSliderFilters#6]
When i take a picture and apply the resizing method, it delays showing the picture in the imageview because it has to resize the pic first in order to display the filters correctly.
I wish there was a way to avoid resizing the image and still show the filters without them being in a wrong orientation?

**Comment by pauljeannot** [comment]
Hi @danieldelouya ,

Actually, I think that the resizing task **must** be done to ensure the user experience with the slider. Indeed, heavy images may quickly lead into memory issues or lags, and resizing is the only way that I know to solve this.

Instead of trying to remove this delay, you should try to add a loading indicator or just let them wait on the previous screen during the computation !

Paul
